services:
  db:
    image: postgres:18.4
    environment:
      POSTGRES_USER: linuquest_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linuquest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: