services:
  db:
    image: postgres:18.4
    environment:
      POSTGRES_USER: linuquest_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linuquest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://linuquest_user:password@db:5432/linuquest
      JWT_SECRET: dev_token
    depends_on:
      - db

volumes:
  postgres_data: